import type { SectionConfig, SettingsConfig } from './types.js';

export const CONFIG = Object.freeze({
    APP_VERSION: '1.1.2',
    STORAGE_KEYS: Object.freeze({
        RULES_2024: 'rules2024',
        OPTIONAL: 'optional',
        HOMEBREW: 'homebrew',
        THEME: 'theme',
        MODE: 'mode',
        REDUCE_MOTION: 'reduceMotion',
        WAKE_LOCK: 'wakeLock',
        DENSITY: 'density',
        COOKIES_ACCEPTED: 'cookiesAccepted',
        FAVORITES: 'userFavorites',
        NOTES: 'userNotes',
        SECTION_STATES: 'sectionStates',
        ONBOARDING_COMPLETED: 'onboardingCompleted',
    } as const),
    SESSION_STORAGE_KEYS: Object.freeze({
        RULESET_CHANGED: 'rulesetChanged',
        UI_SESSION: 'uiSession',
        COOKIES_REMINDER_DISMISSED: 'cookiesReminderDismissed',
    } as const),
    ELEMENT_IDS: Object.freeze({
        POPUP_CONTAINER: 'popup-container',
        COOKIE_NOTICE: 'cookie-notice',
        ACCEPT_COOKIES_BTN: 'accept-cookies',
        REMIND_COOKIES_LATER_BTN: 'remind-cookies-later',
        COPYRIGHT_YEAR: 'copyright-year',
        APP_VERSION_DISPLAY: 'app-version-display',
        CLOSE_ALL_POPUPS_BTN: 'close-all-popups-btn',
        FAVORITES_CONTAINER: 'favorites-container',
        FAVORITES_PLACEHOLDER: 'favorites-placeholder',
        SECTION_FAVORITES: 'section-favorites',
        ARIA_ANNOUNCER: 'aria-announcer',
        MAIN_SCROLL_AREA: 'main-scroll-area',
        RULE_ITEM_TEMPLATE: 'rule-item-template',
        POPUP_TEMPLATE: 'popup-template',
        THEME_SELECT: 'theme-select',
        THEME_STYLESHEET: 'theme-stylesheet',
        SKELETON_LOADER: 'skeleton-loader',
        APP_CONTAINER: 'app-container',
        NOTIFICATION_CONTAINER: 'notification-container',
        REPORT_RULE_BTN: 'report-rule-btn',
        EXPORT_NOTES_BTN: 'export-notes-btn',
        IMPORT_NOTES_BTN: 'import-notes-btn',
        IMPORT_NOTES_INPUT: 'import-notes-input',
        DENSITY_SELECT: 'density-select',
        BACK_TO_TOP_BTN: 'back-to-top-btn',
        MINIMIZED_BAR: 'minimized-popups-bar',
        SHORTCUTS_MODAL: 'keyboard-shortcuts-modal',
        ONBOARDING_OVERLAY: 'onboarding-overlay',
        PRINT_BTN: 'print-mode-btn',
    } as const),
    THEME_CONFIG: Object.freeze({
        PATH: 'themes/',
        MANIFEST: 'themes/themes.json',
    } as const),
    DATA_FILES: Object.freeze(['movement', 'action', 'bonus_action', 'reaction', 'condition', 'environment'] as const),
    SECTION_CONFIG: Object.freeze([
        { id: 'basic-movement', dataKey: 'movement', type: 'Move' },
        { id: 'basic-actions', dataKey: 'action', type: 'Action' },
        { id: 'basic-bonus-actions', dataKey: 'bonus_action', type: 'Bonus action' },
        { id: 'basic-reactions', dataKey: 'reaction', type: 'Reaction' },
        { id: 'basic-conditions', dataKey: 'condition', type: 'Condition' },
        { id: 'environment-obscurance', dataKey: 'environment_obscurance', type: 'Environment' },
        { id: 'environment-light', dataKey: 'environment_light', type: 'Environment' },
        { id: 'environment-vision', dataKey: 'environment_vision', type: 'Environment' },
        { id: 'environment-cover', dataKey: 'environment_cover', type: 'Environment' },
        { id: 'environment-other', dataKey: 'environment_other', type: 'Environment' },
    ] as const) as readonly SectionConfig[],
    SETTINGS_CONFIG: Object.freeze([
        { id: 'optional-switch', key: 'OPTIONAL', stateProp: 'showOptional', type: 'checkbox' },
        { id: 'homebrew-switch', key: 'HOMEBREW', stateProp: 'showHomebrew', type: 'checkbox' },
        { id: 'rules2024-switch', key: 'RULES_2024', stateProp: 'use2024Rules', type: 'checkbox' },
        { id: 'reduce-motion-switch', key: 'REDUCE_MOTION', stateProp: 'reduceMotion', type: 'checkbox' },
        { id: 'wakelock-switch', key: 'WAKE_LOCK', stateProp: 'keepScreenOn', type: 'checkbox' },
        { id: 'theme-select', key: 'THEME', stateProp: 'theme', type: 'select' },
        { id: 'mode-switch', key: 'MODE', stateProp: 'darkMode', type: 'checkbox' },
        { id: 'density-select', key: 'DENSITY', stateProp: 'density', type: 'select' },
    ] as const) as readonly SettingsConfig[],
    CSS: Object.freeze({
        FATAL_ERROR: 'fatal-error-message',
        MOTION_REDUCED: 'motion-reduced',
        ITEM_CLASS: 'item',
        ITEM_SIZE_CLASS: 'itemsize',
        IS_DRAGGING: 'is-dragging',
        IS_ACTIVE: 'is-active',
        IS_CLOSING: 'is-closing',
        IS_VISIBLE: 'is-visible',
        IS_FAVORITED: 'is-favorited',
        IS_COLLAPSED: 'is-collapsed',
        LINK_DISABLED: 'is-disabled',
        POPUP_WINDOW: 'popup-window',
        POPUP_MODAL: 'is-modal',
        POPUP_MINIMIZED: 'is-minimized',
        POPUP_CONTAINER_MODAL_OPEN: 'modal-open',
        POPUP_CLOSE_BTN: 'popup-close-btn',
        POPUP_MINIMIZE_BTN: 'popup-minimize-btn',
        SECTION_CONTAINER: 'section-container',
        HIDDEN: 'hidden',
        SECTION_TITLE: 'section-title',
        SECTION_CONTENT: 'section-content',
        IS_FOCUSED: 'is-focused',
        DRAG_OVER: 'drag-over',
        PRINT_MODE: 'print-mode',
    } as const),
    DEFAULTS: Object.freeze({
        ICON: '', TITLE: '[Untitled Rule]', RULE_TYPE: 'Standard rule', THEME: 'original',
    } as const),
    ATTRIBUTES: Object.freeze({
        RULE_TYPE: 'data-rule-type',
        FILTERABLE: 'data-filterable',
        POPUP_ID: 'data-popup-id',
        RENDERED: 'data-rendered',
        SECTION_KEY: 'data-section',
        ICON: 'data-icon',
    } as const),
    UI_STRINGS: Object.freeze({
        NOTE_STATUS_SAVING: 'Saving...',
        NOTE_STATUS_SAVED: '✓ Saved',
        RULE_NOT_FOUND: 'The requested rule could not be found.',
    } as const),
    DEBOUNCE_DELAY: { RESIZE_MS: 200, NOTE_AUTOSAVE_MS: 750 } as const,
    ANIMATION_DURATION: {
        ITEM_DELAY_MS: 20, POPUP_MS: 200, NOTE_FADEOUT_MS: 2000, NOTIFICATION_MS: 4000, SECTION_TRANSITION_MS: 350,
    } as const,
    IMPORT_LIMITS: {
        MAX_NOTES: 500, MAX_NOTE_SIZE_BYTES: 10_240, MAX_FILE_SIZE_BYTES: 5_242_880,
    } as const,
    LAYOUT: {
        DESKTOP_BREAKPOINT_MIN_PX: 1024,
        POPUP_CASCADE_OFFSET_PX: 30,
        POPUP_CASCADE_WRAP_COUNT: 10,
        POPUP_Z_INDEX_BASE: 1000,
        POPUP_VIEWPORT_PADDING_PX: 8,
        POPUP_MIN_WIDTH_PX: 300,
        POPUP_MIN_HEIGHT_PX: 200,
    } as const,
});
